const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');
const semanticEmbeddings = require('wink-embeddings-sg-100d');

function roundValue(value) {
  return Math.round(value * 1000000) / 1000000;
}

function dotProduct(left, right) {
  let total = 0;
  for (let index = 0; index < left.length; index += 1) {
    total += left[index] * right[index];
  }
  return total;
}

function normalizeVector(vector) {
  const magnitude = Math.sqrt(dotProduct(vector, vector));
  if (!magnitude) {
    return vector.map(() => 0);
  }

  return vector.map((value) => roundValue(value / magnitude));
}

function averageVectors(vectors) {
  if (!vectors.length) {
    return [];
  }

  const sums = new Array(vectors[0].length).fill(0);
  for (const vector of vectors) {
    for (let index = 0; index < vector.length; index += 1) {
      sums[index] += vector[index];
    }
  }

  return sums.map((value) => value / vectors.length);
}

function cosineSimilarity(left, right) {
  return dotProduct(left, right);
}

function renderModule(payload) {
  return `// Generated by scripts/buildSemanticFallback.js
// Compact offline semantic fallback data for mood routing.

const SEMANTIC_FALLBACK_DATA = ${JSON.stringify(payload, null, 2)};

export {
  SEMANTIC_FALLBACK_DATA,
};
`;
}

function getEmbeddingVector(word, dimensions) {
  const rawVector = semanticEmbeddings.vectors[word];
  if (!Array.isArray(rawVector) || rawVector.length < dimensions) {
    return null;
  }

  const vector = rawVector.slice(0, dimensions);
  return normalizeVector(vector);
}

function buildBucketPrototypes(bucketVocab, dimensions) {
  const prototypes = {};
  const metadata = {};

  for (const [bucket, words] of Object.entries(bucketVocab)) {
    if (bucket === 'unknown') {
      continue;
    }

    const uniqueWords = [...new Set(words)];
    const availableSeedWords = [];
    const missingSeedWords = [];
    const seedVectors = [];

    for (const word of uniqueWords) {
      const vector = getEmbeddingVector(word, dimensions);
      if (vector) {
        availableSeedWords.push(word);
        seedVectors.push(vector);
      } else {
        missingSeedWords.push(word);
      }
    }

    if (!seedVectors.length) {
      continue;
    }

    prototypes[bucket] = normalizeVector(averageVectors(seedVectors));
    metadata[bucket] = {
      availableSeedCount: availableSeedWords.length,
      missingSeedCount: missingSeedWords.length,
      availableSeedWords,
    };
  }

  return {
    prototypes,
    metadata,
  };
}

function rankBuckets(vector, bucketPrototypes) {
  return Object.entries(bucketPrototypes)
    .map(([bucket, prototype]) => ({
      bucket,
      score: cosineSimilarity(vector, prototype),
    }))
    .sort((left, right) => right.score - left.score || left.bucket.localeCompare(right.bucket));
}

function buildInputVectors({
  bucketVocab,
  bucketPrototypes,
  buildSettings,
  dimensions,
}) {
  const allowedWordPattern = new RegExp(buildSettings.allowedWordPattern);
  const handcraftedWords = new Set(
    Object.entries(bucketVocab)
      .filter(([bucket]) => bucket !== 'unknown')
      .flatMap(([, words]) => words)
  );
  const inputVectors = new Map();
  let candidateWordCount = 0;

  for (const word of handcraftedWords) {
    const vector = getEmbeddingVector(word, dimensions);
    if (vector) {
      inputVectors.set(word, vector);
    }
  }

  for (const word of semanticEmbeddings.words) {
    if (!allowedWordPattern.test(word) || word.length < buildSettings.minWordLength) {
      continue;
    }

    const vector = getEmbeddingVector(word, dimensions);
    if (!vector) {
      continue;
    }

    candidateWordCount += 1;
    const rankedBuckets = rankBuckets(vector, bucketPrototypes);
    const [bestMatch] = rankedBuckets;
    if (!bestMatch) {
      continue;
    }

    if (bestMatch.score >= buildSettings.pruneMinSimilarity) {
      inputVectors.set(word, vector);
    }
  }

  return {
    inputVectors: Object.fromEntries(inputVectors.entries()),
    metadata: {
      handcraftedInputVectorCount: [...handcraftedWords].filter((word) => inputVectors.has(word)).length,
      candidateWordCount,
      retainedInputVectorCount: inputVectors.size,
    },
  };
}

async function main() {
  const rootDir = path.join(__dirname, '..');
  const snapshotModule = await import(pathToFileURL(
    path.join(rootDir, 'data', 'vendor', 'moodSynonymSnapshot.js')
  ).href);
  const configModule = await import(pathToFileURL(
    path.join(rootDir, 'data', 'vendor', 'semanticFallbackConfig.js')
  ).href);

  const { BUCKET_VOCAB } = snapshotModule;
  const {
    SEMANTIC_BUILD_SETTINGS,
    SEMANTIC_FALLBACK_SETTINGS,
  } = configModule;

  const dimensions = semanticEmbeddings.dimensions;
  const {
    prototypes: bucketPrototypes,
    metadata: bucketMetadata,
  } = buildBucketPrototypes(BUCKET_VOCAB, dimensions);

  const {
    inputVectors,
    metadata: inputMetadata,
  } = buildInputVectors({
    bucketVocab: BUCKET_VOCAB,
    bucketPrototypes,
    buildSettings: SEMANTIC_BUILD_SETTINGS,
    dimensions,
  });

  const payload = {
    version: 2,
    dimensions,
    settings: SEMANTIC_FALLBACK_SETTINGS,
    bucketPrototypes,
    inputVectors,
    metadata: {
      source: 'wink-embeddings-sg-100d',
      embeddingVocabularySize: semanticEmbeddings.size,
      handcraftedBucketCount: Object.keys(BUCKET_VOCAB).filter((bucket) => bucket !== 'unknown').length,
      bucketMetadata,
      ...inputMetadata,
    },
  };

  const outputPath = path.join(rootDir, 'data', 'vendor', 'semanticFallbackData.js');
  fs.writeFileSync(outputPath, renderModule(payload), 'utf8');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
