const fs = require('fs');
const path = require('path');

const BUCKET_ORDER = [
  'amazed',
  'angry',
  'anxious',
  'awkward',
  'calm',
  'confused',
  'distracted',
  'disgusted',
  'frustrated',
  'grateful',
  'guilty',
  'happy',
  'hopeful',
  'hungry',
  'jealous',
  'lonely',
  'loving',
  'numb',
  'proud',
  'sad',
  'stressed',
  'surprised',
  'tired',
  'wired',
  'unknown',
];

const BASE_OPEN_FALLBACK_CANDIDATES = {
  amazed: ['flabbergasted', 'thunderstruck', 'transfixed'],
  angry: ['apoplectic', 'rankled', 'riled'],
  anxious: ['angst', 'disquieted', 'perturbed'],
  awkward: ['bumbling', 'gauche', 'graceless'],
  calm: ['peaceable', 'selfpossessed', 'untroubled'],
  confused: ['addled', 'confounded', 'mystified'],
  distracted: ['distrait', 'forgetful', 'unmindful'],
  disgusted: ['appalled', 'nauseous'],
  frustrated: ['foiled', 'hampered', 'hindered'],
  grateful: ['appreciatory', 'beholden', 'indebted'],
  guilty: ['blameworthy', 'compunctious'],
  happy: ['exultant', 'jolly', 'overjoyed'],
  hopeful: ['sanguine', 'trustful'],
  hungry: ['unsatiated'],
  jealous: ['invidious'],
  lonely: ['forsaken'],
  loving: ['amorous', 'solicitous', 'tenderhearted'],
  numb: ['anhedonic', 'dissociated', 'inert'],
  proud: ['selfrespecting', 'triumphal'],
  sad: ['dejected', 'heartsick', 'joyless', 'morose'],
  stressed: ['beleaguered', 'hectic', 'overtaxed'],
  surprised: ['stupefied'],
  tired: ['enervated', 'logy', 'somnolent'],
  wired: ['frenetic', 'hyperalert', 'hyped'],
  unknown: [],
};

const overridesPath = path.join(__dirname, '..', 'data', 'vendor', 'openFallbackOverrides.json');
const outputPath = path.join(__dirname, '..', 'data', 'vendor', 'openFallbackVocab.js');

function normalizeWord(value) {
  return String(value || '')
    .trim()
    .toLowerCase();
}

function isValidFallbackWord(value) {
  return /^[a-z0-9]+$/.test(value);
}

function uniqueSorted(values) {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right));
}

function loadOverrides() {
  const raw = fs.readFileSync(overridesPath, 'utf8');
  return JSON.parse(raw);
}

function buildFallbackVocab() {
  const overrides = loadOverrides();
  const include = overrides.include || {};
  const exclude = overrides.exclude || {};
  const globalExclude = new Set((exclude.global || []).map(normalizeWord));
  const excludeByBucket = exclude.byBucket || {};

  const candidateMap = Object.fromEntries(
    BUCKET_ORDER.map((bucket) => {
      const combined = [
        ...(BASE_OPEN_FALLBACK_CANDIDATES[bucket] || []),
        ...(include[bucket] || []),
      ]
        .map(normalizeWord)
        .filter(Boolean)
        .filter(isValidFallbackWord)
        .filter((word) => !globalExclude.has(word))
        .filter((word) => !((excludeByBucket[bucket] || []).map(normalizeWord).includes(word)));

      return [bucket, uniqueSorted(combined)];
    })
  );

  const wordToBuckets = new Map();
  for (const bucket of BUCKET_ORDER) {
    for (const word of candidateMap[bucket]) {
      if (!wordToBuckets.has(word)) {
        wordToBuckets.set(word, []);
      }
      wordToBuckets.get(word).push(bucket);
    }
  }

  const conflictingWords = new Set(
    [...wordToBuckets.entries()]
      .filter(([, buckets]) => buckets.length > 1)
      .map(([word]) => word)
  );

  const finalMap = Object.fromEntries(
    BUCKET_ORDER.map((bucket) => [
      bucket,
      candidateMap[bucket].filter((word) => !conflictingWords.has(word)),
    ])
  );

  return {
    finalMap,
    conflictingWords: [...conflictingWords].sort((left, right) => left.localeCompare(right)),
  };
}

function renderModule(vocab) {
  const lines = [
    '// Generated by scripts/buildOpenFallbackVocab.js',
    '// Lower-priority open lexical fallback terms for mood routing.',
    '// Handcrafted BUCKET_VOCAB remains the primary routing source of truth.',
    '',
    'const OPEN_FALLBACK_VOCAB = {',
  ];

  for (const bucket of BUCKET_ORDER) {
    const words = vocab[bucket] || [];
    const renderedWords = words.length === 0
      ? '[]'
      : `[\n${words.map((word) => `    '${word}',`).join('\n')}\n  ]`;
    lines.push(`  ${bucket}: ${renderedWords},`);
  }

  lines.push('};', '', 'export {', '  OPEN_FALLBACK_VOCAB,', '};', '');
  return `${lines.join('\n')}`;
}

function main() {
  const { finalMap, conflictingWords } = buildFallbackVocab();
  fs.writeFileSync(outputPath, renderModule(finalMap), 'utf8');

  if (conflictingWords.length > 0) {
    console.warn(
      `Skipped ${conflictingWords.length} conflicting fallback terms: ${conflictingWords.join(', ')}`
    );
  }
}

main();
