const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');
const semanticEmbeddings = require('wink-embeddings-sg-100d');

function roundValue(value) {
  return Math.round(value * 1000000) / 1000000;
}

function dotProduct(left, right) {
  let total = 0;
  for (let index = 0; index < left.length; index += 1) {
    total += left[index] * right[index];
  }
  return total;
}

function normalizeVector(vector) {
  const magnitude = Math.sqrt(dotProduct(vector, vector));
  if (!magnitude) {
    return vector.map(() => 0);
  }

  return vector.map((value) => roundValue(value / magnitude));
}

function averageVectors(vectors) {
  if (!vectors.length) {
    return [];
  }

  const sums = new Array(vectors[0].length).fill(0);
  for (const vector of vectors) {
    for (let index = 0; index < vector.length; index += 1) {
      sums[index] += vector[index];
    }
  }

  return sums.map((value) => value / vectors.length);
}

function cosineSimilarity(left, right) {
  return dotProduct(left, right);
}

function renderModule(payload) {
  return `// Generated by scripts/buildSemanticFallback.js
// Generated runtime vector embeddings fallback data for mood routing.

const SEMANTIC_FALLBACK_DATA = ${JSON.stringify(payload, null, 2)};

export {
  SEMANTIC_FALLBACK_DATA,
};
`;
}

function getEmbeddingVector(word, dimensions) {
  const rawVector = semanticEmbeddings.vectors[word];
  if (!Array.isArray(rawVector) || rawVector.length < dimensions) {
    return null;
  }

  const vector = rawVector.slice(0, dimensions);
  return normalizeVector(vector);
}

function buildBucketPrototypes(bucketVocab, dimensions, prototypeAnchors = {}) {
  const prototypes = {};
  const bucketAnchors = {};
  const metadata = {};
  const maxAnchorsPerBucket = Number.isFinite(prototypeAnchors.maxAnchorsPerBucket)
    ? prototypeAnchors.maxAnchorsPerBucket
    : null;

  for (const [bucket, words] of Object.entries(bucketVocab)) {
    if (bucket === 'unknown') {
      continue;
    }

    const anchorWords = [...new Set((prototypeAnchors[bucket] || []).map((word) => String(word || '').toLowerCase()))]
      .slice(0, maxAnchorsPerBucket || undefined);
    const uniqueWords = anchorWords.length > 0 ? anchorWords : [...new Set(words)];
    const availableSeedWords = [];
    const missingSeedWords = [];
    const seedVectors = [];

    for (const word of uniqueWords) {
      const vector = getEmbeddingVector(word, dimensions);
      if (vector) {
        availableSeedWords.push(word);
        seedVectors.push(vector);
      } else {
        missingSeedWords.push(word);
      }
    }

    if (!seedVectors.length) {
      continue;
    }

    prototypes[bucket] = normalizeVector(averageVectors(seedVectors));
    bucketAnchors[bucket] = availableSeedWords.map((word, index) => ({
      word,
      vector: seedVectors[index],
    }));
    metadata[bucket] = {
      prototypeSource: anchorWords.length > 0 ? 'anchors' : 'bucket-vocab',
      availableSeedCount: availableSeedWords.length,
      missingSeedCount: missingSeedWords.length,
      availableSeedWords,
      missingSeedWords,
    };
  }

  return {
    prototypes,
    bucketAnchors,
    metadata,
  };
}

function buildRuntimeKeepWords({
  buildSettings,
  prototypeAnchors,
}) {
  const allowedWordPattern = new RegExp(buildSettings.allowedWordPattern);
  const keepWords = new Set();

  const addWord = (word) => {
    const normalized = String(word || '').toLowerCase().trim();
    if (
      !normalized
      || !allowedWordPattern.test(normalized)
      || normalized.length < buildSettings.minWordLength
    ) {
      return;
    }

    keepWords.add(normalized);
  };

  Object.values(prototypeAnchors)
    .flat()
    .forEach(addWord);

  (buildSettings.forceIncludeWords || []).forEach(addWord);

  Object.values(buildSettings.runtimeKeepWordsByBucket || {})
    .flat()
    .forEach(addWord);

  return [...keepWords];
}

function buildInputVectors({
  keepWords,
  dimensions,
}) {
  const inputVectors = new Map();
  let missingKeepWordCount = 0;

  for (const word of keepWords) {
    const vector = getEmbeddingVector(word, dimensions);
    if (vector) {
      inputVectors.set(word, vector);
    } else {
      missingKeepWordCount += 1;
    }
  }

  return {
    inputVectors: Object.fromEntries(inputVectors.entries()),
    metadata: {
      requestedKeepWordCount: keepWords.length,
      missingKeepWordCount,
      retainedInputVectorCount: inputVectors.size,
    },
  };
}

async function main() {
  const rootDir = path.join(__dirname, '..');
  const snapshotModule = await import(pathToFileURL(
    path.join(rootDir, 'data', 'runtime', 'moodBucketVocabulary.js')
  ).href);
  const configModule = await import(pathToFileURL(
    path.join(rootDir, 'data', 'build', 'semanticFallbackConfig.js')
  ).href);
  const seedModule = await import(pathToFileURL(
    path.join(rootDir, 'data', 'build', 'semanticSeedVocabulary.js')
  ).href);

  const { BUCKET_VOCAB } = snapshotModule;
  const {
    SEMANTIC_BUILD_SETTINGS,
    SEMANTIC_FALLBACK_SETTINGS,
  } = configModule;
  const { EMBEDDING_SEEDS } = seedModule;

  const dimensions = semanticEmbeddings.dimensions;
  const {
    prototypes: bucketPrototypes,
    bucketAnchors,
    metadata: bucketMetadata,
  } = buildBucketPrototypes(BUCKET_VOCAB, dimensions, {
    ...EMBEDDING_SEEDS,
    maxAnchorsPerBucket: SEMANTIC_BUILD_SETTINGS.maxAnchorsPerBucket,
  });

  const runtimeKeepWords = buildRuntimeKeepWords({
    buildSettings: SEMANTIC_BUILD_SETTINGS,
    prototypeAnchors: EMBEDDING_SEEDS,
  });

  const {
    inputVectors,
    metadata: inputMetadata,
  } = buildInputVectors({
    keepWords: runtimeKeepWords,
    dimensions,
  });

  const payload = {
    version: 2,
    dimensions,
    settings: SEMANTIC_FALLBACK_SETTINGS,
    bucketPrototypes,
    bucketAnchors,
    inputVectors,
    metadata: {
      source: 'wink-embeddings-sg-100d',
      embeddingVocabularySize: semanticEmbeddings.size,
      deterministicBucketCount: Object.keys(BUCKET_VOCAB).filter((bucket) => bucket !== 'unknown').length,
      semanticSeedBucketCount: Object.keys(EMBEDDING_SEEDS).filter((bucket) => bucket !== 'unknown').length,
      runtimeKeepWordCount: runtimeKeepWords.length,
      bucketMetadata,
      ...inputMetadata,
    },
  };

  const outputPath = path.join(rootDir, 'data', 'runtime', 'semanticFallbackData.js');
  fs.writeFileSync(outputPath, renderModule(payload), 'utf8');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
